site_name: Karl Meisner-Jensen
docs_dir: .
site_dir: ../site
repo_url: httpshttps://github.com/TheGoldenChicken/the_kid_bible

theme:
  language: en
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox
  - same-dir

extra:
  social:
    - icon: material/email
      link: mailto:karlmeisner@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/TheGoldenChicken
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/karl-meisner-jensen-012a31194/

nav:
  - Home: README.md
  # - Publications: publications.md
  # - Teaching: teaching.md
  # - Code: code.md
  # - CV: cv.md
